### PR TITLE
Remove unused and outdated files

### PR DESCRIPTION
**Pull request by intendo**
@sobolevnrm, please review and add any other files that are no longer used.

### CODE REVIEW

**Comment by intendo** [comment]
There is a problem with all the external projects. Every one of them include `"tools/windows/configuration headers"` in an `include_directories()` statement in a CMakeLists.txt file. 

```
./externals/bem/CMakeLists.txt:        ../../tools/windows/configuration\ headers/
./externals/geoflow_c/src/CMakeLists.txt:         ../../../tools/windows/configuration\ headers/
./externals/pb_s_am/pbsam/src/CMakeLists.txt:    ../../../../tools/windows/configuration\ headers/
./externals/pb_s_am/pbam/src/CMakeLists.txt:                      ../../../../tools/windows/configuration\ headers/
```

This is where they all find the `apbscfg.h` file that was generated by some `autoheader` from some `configure.ac`. This was done statically about 7 years ago when the `APBS_VERSION` was `1.3.1` according to the `PACKAGE_STRING` defined in the `apbscfg.h` file.

Every entry in the `apbscfg.h` file is `UNDEF` except for `PACKAGE_STRING`.

The build errors all follow the same pattern:
```
make[6]: Leaving directory '/home/runner/work/apbs/apbs/build/geoflow-prefix/src/geoflow-build'
                 from /home/runner/work/apbs/apbs/externals/geoflow_c/src/GeometricFlowWrap.cpp:54:
/home/runner/work/apbs/apbs/externals/geoflow_c/src/../../../src/generic/valist.h:65:10: fatal error: apbscfg.h: No such file or directory
 #include "apbscfg.h"
          ^~~~~~~~~~~
compilation terminated.
```

Maybe the appropriate fix would be to change all the external CMakeLists.txt file to replace the `"tools/windows/configuration\ headers/"` to `build/src` so they get the "current" `apbscfg.h`.

**Review by sobolevnrm — APPROVED** [review]

**Comment by lwwilson1** [comment]
Looks like the reason this happened is that our wrappers for APBS all rely on the Valist struct for accessing molecule information. The header for that file includes apbscfg.h, and I think we all picked up from geoflow that one could include ../../tools/windows/configuration\ headers/ to include it. Including build/src instead works totally fine, at least for bem.

**Comment by intendo** [comment]
I finally got everything to build (except PYTHON) and the problem with finding the python executable during test in #108

**Comment by intendo** [comment]
This closes #101

**Pull request merged**
