### PR TITLE
Nsoblath/issue 212

### LINKED ISSUE #212: Error while loading shared libraries: libpython3.9.so.1.0
**Describe the bug**
I downloaded APBS-3.4.0.Linux.zip. I unzipped. I renamed the directory to apbs. I then moved the directory to /home/my_name/apbs.
I edited the .bashrc to include the following.

export LD_LIBRARY_PATH=$HOME/apbs/lib:${LD_LIBRARY_PATH}
export PATH=$HOME/apbs/bin:${PATH}

When I try to run apbs I get the following error:

`apbs: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
`

My python version.
python --version
Python 3.9.10

**To Reproduce**
1. Unzip and rename APBS-3.4.0.Linux.zip to apbs 
2.  Move to $HOME.
3. Edit .bashrc to change paths
3. Run apbs

**Expected behavior**
I expected APBS to prompt for expected variables

**Screenshots**
None

**Desktop (please complete the following information):**
 - Ubuntu 18.04
-  Python 3.9.10

-None

**Additional context**
-None

### PR DESCRIPTION
**Pull request by nsoblath**
Statically link Python in Mac and Linux builds.

Closes #212

### CODE REVIEW

**Comment by nsoblath** [comment]
Update: Added explicit linking to thread library, libdl, and libutil (the latter two for non-Windows).  Test builds work.

**Comment by nsoblath** [comment]
Update [actually from 3/21/22]: On Linux the static linking to Python is actually working.  On Mac, it appears to be statically linking libpython3.9.a, but the Framework still shows up when I call `otool -L` on the apbs executable.  The test run works without separately installing Python because the Mac GitHub-hosted runner already has Python 3.9 installed.

**Comment by nsoblath** [comment]
Update: Mac build solved by linking to the `Intl` and `Iconv` packages (for non-Windows) and the `CoreUtilities` framework for macOS.  At this point, Python has now been statically linked in (see checks below).

Currently the test jobs are not even starting because of some problem with the `build.yaml` job specification.  I'm going to try reverting some of the other changes that were made to that file to test the python linking, and see if that fixes whatever's causing the test job to fail.

Here's the libraries dynamically linked to the apbs binary in the Mac build:
```
➜  bin otool -L apbs
apbs:
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
```

And here are the libraries dynamically linked to the apbs binary in the linux build:
```
root@109cdbd4dfe5:/apbs/bin# ldd apbs
	linux-vdso.so.1 (0x00007ffecf1f5000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fba841cf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fba841c9000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fba83fe7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fba83fc4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fba83e75000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fba83e5a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fba83c66000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fba85e93000)
```

**Review by intendo — APPROVED** [review]

**Comment by alexreg** [comment]
Unfortunately, this still seems to be an issue in the 3.4.1 release.

```
Performing C SOURCE FILE Test Intl_IS_BUILT_IN failed with the following output:
Change Dir: /tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp

Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_799a3/fast && /opt/homebrew/bin/gmake  -f CMakeFiles/cmTC_799a3.dir/build.make CMakeFiles/cmTC_799a3.dir/build
gmake[1]: Entering directory '/private/tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_799a3.dir/src.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/gcc-12 -DIntl_IS_BUILT_IN  -fopenmp -fPIC  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -o CMakeFiles/cmTC_799a3.dir/src.c.o -c /tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_799a3
/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_799a3.dir/link.txt --verbose=1
/opt/homebrew/Library/Homebrew/shims/mac/super/gcc-12 -fopenmp -fPIC  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_799a3.dir/src.c.o -o cmTC_799a3 
Undefined symbols for architecture arm64:
  "_libintl_dcgettext", referenced from:
      _main in src.c.o
  "_libintl_dgettext", referenced from:
      _main in src.c.o
  "_libintl_gettext", referenced from:
      _main in src.c.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_799a3.dir/build.make:99: cmTC_799a3] Error 1
gmake[1]: Leaving directory '/private/tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_799a3/fast] Error 2


Source file was:
#include <libintl.h>
int main(void) {
  gettext("");
  dgettext("", "");
  dcgettext("", "", 0);
  return 0;
}

Performing C SOURCE FILE Test Iconv_IS_BUILT_IN failed with the following output:
Change Dir: /tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp

Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_a634d/fast && /opt/homebrew/bin/gmake  -f CMakeFiles/cmTC_a634d.dir/build.make CMakeFiles/cmTC_a634d.dir/build
gmake[1]: Entering directory '/private/tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a634d.dir/src.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/gcc-12 -DIconv_IS_BUILT_IN  -fopenmp -fPIC  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -o CMakeFiles/cmTC_a634d.dir/src.c.o -c /tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_a634d
/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a634d.dir/link.txt --verbose=1
/opt/homebrew/Library/Homebrew/shims/mac/super/gcc-12 -fopenmp -fPIC  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_a634d.dir/src.c.o -o cmTC_a634d 
Undefined symbols for architecture arm64:
  "_libiconv", referenced from:
      _main in src.c.o
  "_libiconv_close", referenced from:
      _main in src.c.o
  "_libiconv_open", referenced from:
      _main in src.c.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_a634d.dir/build.make:99: cmTC_a634d] Error 1
gmake[1]: Leaving directory '/private/tmp/apbs-20220926-39068-n0ircz/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_a634d/fast] Error 2


Source file was:

      #include <stddef.h>
      #include <iconv.h>
      int main() {
        char *a, *b;
        size_t i, j;
        iconv_t ic;
        ic = iconv_open("to", "from");
        iconv(ic, &a, &i, &b, &j);
        iconv_close(ic);
      }
```

Incidentally, I also needed to pass `-DBLA_VENDOR=OpenBLAS -DCMAKE_C_FLAGS=-fopenmp` to CMake to get it this far, as well as making sure OpenMP is installed (despite `-DENABLE_OPENMP=OFF`).

**Comment by alexreg** [comment]
@sobolevnrm If you would, please.

**Pull request merged**
