### PR TITLE
Additional NOsh kernels

### PR DESCRIPTION
**Pull request by ashermancinelli**
Ports all but two NOsh kernels. Only requesting @intendo's review since this is so small, but I figured this still constitutes it's own PR before moving on to other classes.

### CODE REVIEW

**Comment by intendo** [comment]
@ashermancinelli I think you need to do a `git pull` from master since I fixed the git submodule for pybind11. I think that is why there is a conflict with `.gitmodules` and `externals/pybind11`.

**Comment by ashermancinelli** [comment]
Perfect, thank you for your work on this @intendo!

**Review by intendo — APPROVED** [review]

**Comment by intendo** [comment]
Still need to figure out how to get pybind11 installed or made available in Appveyor and Github Actions

**Comment by ashermancinelli** [comment]
I can take case of the github build, but I have no idea how to build with windows stuff. If you want to wait for me to do this in github actions before doing the same for appveyor, would you make an issue to track this? Thank you!

**Comment by intendo** [comment]
If you get it working with Github Actions, I can figure out how to make it work with Appveyor.

**Pull request merged**
