### PR TITLE
Integration of new TABI-PB

### PR DESCRIPTION
**Pull request by lwwilson1**
This pull request addresses integration of a new TABI-PB. 

The new TABI-PB has the following improvements/ changes:
+ Replaces the O(N log N) Taylor treecode with an O(N) dual tree traversal fast summation method based on polynomial interpolation
+ Rewritten in (pretty readable) C++
+ About a 40% decrease in memory usage for problems of comparable size
+ Roughly 4 to 6x faster for problems of comparable accuracy level

I've been able to build it and successfully pass the BEM tests on the following setups:

+ macOS Catalina 10.15.7 
  + GCC 10.2.0
  + clang 11.0.3
+ CentOS 7  
  + GCC 8.2.0
  + PGI 20.1

I unfortunately have no way to test on Windows, so I'd be super grateful if somebody who has access to a Windows machine could try it out. I also get build failures using Intel compilers (18.0.5, 19.1) on CentOS 7, but this isn't related to TABI-PB (see issue #105).

### CODE REVIEW

**Review by sobolevnrm — APPROVED** [review]

**Comment by intendo** [comment]
@sobolevnrm @lwwilson1 this fails with the same problem of not being able to find the MALOC include files:

```
[ 16%] Building CXX object src/CMakeFiles/TABIPBlib.dir/molecule.cpp.o
cd /home/runner/work/apbs/apbs/build/bem-prefix/src/bem-build/src && /usr/bin/g++  -DTABIPB_APBS -I/home/runner/work/apbs/apbs/externals/bem/src/../../../src -I/home/runner/work/apbs/apbs/externals/bem/src/../../../build/src -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/base -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/vsys -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/vsh -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/psh  -O2 -g -DNDEBUG   -O3 -o CMakeFiles/TABIPBlib.dir/molecule.cpp.o -c /home/runner/work/apbs/apbs/externals/bem/src/molecule.cpp
In file included from /home/runner/work/apbs/apbs/externals/bem/src/../../../src/generic/valist.h:71:0,
                 from /home/runner/work/apbs/apbs/externals/bem/src/molecule.h:12,
                 from /home/runner/work/apbs/apbs/externals/bem/src/molecule.cpp:11:
/home/runner/work/apbs/apbs/externals/bem/src/../../../src/generic/vparam.h:69:10: fatal error: mc/mc.h: No such file or directory
 #include "mc/mc.h"
          ^~~~~~~~~
```

**Comment by lwwilson1** [comment]
> @sobolevnrm @lwwilson1 this fails with the same problem of not being able to find the MALOC include files:
> 
> ```
> [ 16%] Building CXX object src/CMakeFiles/TABIPBlib.dir/molecule.cpp.o
> cd /home/runner/work/apbs/apbs/build/bem-prefix/src/bem-build/src && /usr/bin/g++  -DTABIPB_APBS -I/home/runner/work/apbs/apbs/externals/bem/src/../../../src -I/home/runner/work/apbs/apbs/externals/bem/src/../../../build/src -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/base -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/vsys -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/vsh -I/home/runner/work/apbs/apbs/externals/bem/src/../../../externals/fetk/maloc/src/psh  -O2 -g -DNDEBUG   -O3 -o CMakeFiles/TABIPBlib.dir/molecule.cpp.o -c /home/runner/work/apbs/apbs/externals/bem/src/molecule.cpp
> In file included from /home/runner/work/apbs/apbs/externals/bem/src/../../../src/generic/valist.h:71:0,
>                  from /home/runner/work/apbs/apbs/externals/bem/src/molecule.h:12,
>                  from /home/runner/work/apbs/apbs/externals/bem/src/molecule.cpp:11:
> /home/runner/work/apbs/apbs/externals/bem/src/../../../src/generic/vparam.h:69:10: fatal error: mc/mc.h: No such file or directory
>  #include "mc/mc.h"
>           ^~~~~~~~~
> ```

Hmm, I'm not sure I know why this is. This doesn't happen on either system I've built on. Any ideas for testing/ diagnosing this?

**Comment by intendo** [comment]
@lwwilson1 @sobolevnrm @ashermancinelli The situation is a bit of a catch 22.

Removing the `tools/windows/configuration headers/apbscfg.h` and using the `src/.config/apbscfg.h.in` causes a conflict with the 'Mat' symbol which is defined in the MALOC `externals/fetk/mc/src/bam/mc/mat.h` and the GeoFlow `externals/geoflow_c/src/Mat.h`.

Moving `tools/windows/configuration headers/apbscfg.h` to `tools/apbscfg.h` resolved that problem but now the problem seems to be related to OPENMP or `FLOAT_EPSILON` and `DOUBLE_EPSILON`. The value is computed and displayed correctly in the CMake output but fails in the Windows and Linux version of the build.

MacOS is failing with now failing with a new C99 error not being able to find the LAPACK `xerbla_`

Windows:
```
-- Computing machine epsilon values
-- Floating point epsilon is 2.220446e-16
-- Double precision epsilon is 2.220446e-16
[snip]
"C:\projects\source\build\install.vcxproj" (default target) (1) ->
"C:\projects\source\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\projects\source\build\src\apbs.vcxproj" (default target) (12) ->
"C:\projects\source\build\src\apbs_routines.vcxproj" (default target) (13) ->
(ClCompile target) -> 
  C:\projects\source\src\routines.c(5702,46): error C2065: 'FLOAT_EPSILON': undeclared identifier [C:\projects\source\build\src\apbs_routines.vcxproj]
  C:\projects\source\src\routines.c(5703,48): error C2065: 'DOUBLE_EPSILON': undeclared identifier [C:\projects\source\build\src\apbs_routines.vcxproj]
    432 Warning(s)
    2 Error(s)
Time Elapsed 00:08:06.44
Command exited with code 1
if exist c:\projects\source\build\CMakeFiles\CMakeOutput.log type c:\projects\source\build\CMakeFiles\CMakeOutput.log
The system is: Windows - 10.0.17763 - AMD64
```

Linux:
```
-- Computing machine epsilon values
-- Floating point epsilon is 2.220446e-16
-- Double precision epsilon is 2.220446e-16
[snip]
/home/runner/work/apbs/apbs/src/routines.c: In function ‘dump_options’:
/home/runner/work/apbs/apbs/src/routines.c:5702:33: error: ‘FLOAT_EPSILON’ undeclared (first use in this function); did you mean ‘FLT_EPSILON’?
     printf("FLOAT_EPSILON:%f\n",FLOAT_EPSILON);
                                 ^~~~~~~~~~~~~
                                 FLT_EPSILON
/home/runner/work/apbs/apbs/src/routines.c:5702:33: note: each undeclared identifier is reported only once for each function it appears in
/home/runner/work/apbs/apbs/src/routines.c:5703:34: error: ‘DOUBLE_EPSILON’ undeclared (first use in this function); did you mean ‘DBL_EPSILON’?
     printf("DOUBLE_EPSILON:%f\n",DOUBLE_EPSILON);
                                  ^~~~~~~~~~~~~~
                                  DBL_EPSILON
make[2]: *** [src/CMakeFiles/apbs_routines.dir/routines.c.o] Error 1
```

MacOS:
```
/bin/sh ../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/runner/work/apbs/apbs/externals/fetk/punc/src/superlu -I../../src/aaa_inc -I/Users/runner/work/apbs/apbs/build/fetk/include     -g -O2 -c -o sp_ienv.lo /Users/runner/work/apbs/apbs/externals/fetk/punc/src/superlu/sp_ienv.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/runner/work/apbs/apbs/externals/fetk/punc/src/superlu -I../../src/aaa_inc -I/Users/runner/work/apbs/apbs/build/fetk/include -g -O2 -c /Users/runner/work/apbs/apbs/externals/fetk/punc/src/superlu/sp_ienv.c  -fno-common -DPIC -o .libs/sp_ienv.o
/Users/runner/work/apbs/apbs/externals/fetk/punc/src/superlu/sp_ienv.c:66:5: error: implicit declaration of function 'xerbla_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    xerbla_("sp_ienv", &i);
    ^
1 error generated.
make[6]: *** [sp_ienv.lo] Error 1
```

I am very much chasing my tail.

**Comment by intendo** [comment]
@lwwilson1 can you do the following commands to resolve the conflicts in the merge?

```
git checkout -b lwwilson1-new-tabipb-integration master
git pull https://github.com/lwwilson1/apbs.git new-tabipb-integration
git checkout master
git merge --no-ff lwwilson1-new-tabipb-integration
git push origin master
```

**Comment by lwwilson1** [comment]
Well, the ubuntu and macOS builds finally pass here, but now that I'm seeing a Windows build for the first time, it looks like it fails spectacularly. Nearly every error, if not every, appears to be related to the use of __restrict__, which the Microsoft compiler doesn't like, as it apparently prefers __restrict. I might be able to just use __restrict, since I'm pretty sure GCC and Clang both support this. I'll try something along these lines tomorrow and push again to see if I can get it to work.

**Comment by intendo** [comment]
@lwwilson1 can you use **__restrict** with gcc and clang?
Since it is a c99 standard and not in any C++ standard, the C++ compilers can optionally ignore it or use it. I can't find a consistent way to get it to work the same with all compilers.

You might want to grab a function that uses **__restrict** and try it on https://godbolt.org/ with clang, gcc, and vc++ to see if they produce the same assembly or not.

I know that **restrict** and **const** are different but at least **const** is consistent across compilers so it might be a alternative approach?

**Comment by lwwilson1** [comment]
Looking through compiler explorer, it looks like __restrict is both compiling and doing what I want it to in all three cases (also compiling for PGI and Intel). So I've changed all the `__restrict__`s to `__restrict`s. Looks like that's the more universal compiler extension. 

So after pushing it, it's still building for macOS and ubuntu, but the AppVeyor build failed. It doesn't look like it has anything to do with TABI-PB this time, though. I don't think it even got that far. Looks like it had trouble downloading Swig?

**Comment by intendo** [comment]
@lwwilson1 
The Appveyor problem was trying to download SWIG from SourceForge which occasionally fails (they must not have a retry). Anyway, the build is still failing in the bem area at line 3148 in the output at https://ci.appveyor.com/project/intendo/apbs

**Comment by lwwilson1** [comment]
So it looks like everything is now building correctly with MSVC and the three BEM tests (14, 15, 16) are passing. AppVeyor still failed though... looks like something went wrong on test 18?

**Comment by intendo** [comment]
@lwwilson1 You are correct. The error with the test has been identified in issue #108 

At this point, your code changes look great and I and merge the changes.

**Pull request merged**
